### ISSUE TITLE
ACT 10 PROYECTO FINAL DE WEB 3.0 EQUIPO DINAMITA

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-10-proyecto-final-de-web-30-equipo-2#1]

**Comment by YaelTrinidad** [comment]
[anteproyecto de residencia diciembre supersiuu.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-proyecto-final-de-web-30-equipo-2/files/10220540/anteproyecto.de.residencia.diciembre.supersiuu.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica para calificar el proyecto tiene 23 de 23 puntos , que equivale a 50 %

**Comment by YaelTrinidad** [comment]
Ya corregì el documento, les hice las correcciones al ìndice, los objetivos y las referencias :), El documento lo deje en el mismo comentario anterior.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
